name: deploy to test instance
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/github-workflows/mhealth-apps/
          sudo rm -rf C4C-Web
          sudo mkdir C4C-Web
          sudo chown -R cicd2:cicd2 C4C-Web
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/C4C-Web/
          cd C4C-Web/
          git clone -b master https://github.com/palladiumkenya/C4C-Web.git .
          git status
          # cp  /apps/configs/C4C-Web/.env /apps/github-workflows/mhealth-apps/C4C-Web/
          cp  /apps/configs/C4C-Web/Dockerfile /apps/github-workflows/mhealth-apps/C4C-Web/
          cp  /apps/configs/C4C-Web/default.conf /apps/github-workflows/mhealth-apps/C4C-Web/
          cp -r /apps/configs/C4C-Web/ssl/ /apps/github-workflows/mhealth-apps/C4C-Web/
          cp  /apps/configs/C4C-Web/nginx.conf /apps/github-workflows/mhealth-apps/C4C-Web/
          docker stop cforcweb
          docker rm cforcweb
          docker build -t c4cwebtest:latest .
          docker run -p 7005:443 -d --name=c4cwebtest --restart always c4cwebtest:latest
