name: deploy to test instance
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/C4C-Web/      
          cd /apps/github-workflows/mhealth-apps/C4C-Web/
          git pull origin master
          git status
          cp  /apps/configs/C4C-Web/.env /apps/github-workflows/mhealth-apps/C4C-Web/
          cp  /apps/configs/C4C-Web/Dockerfile /apps/github-workflows/mhealth-apps/C4C-Web/
          cp -r /apps/configs/C4C-Web/nginx/ /apps/github-workflows/mhealth-apps/C4C-Web/
          cp  /apps/configs/C4C-Web/docker-compose.yml /apps/github-workflows/mhealth-apps/C4C-Web/
          docker stop cforcweb
          docker rm cforcweb
          docker build -t cicdapplication/cforcweb:latest .
          docker run -p 7005:443 -d --name=cforcweb --restart always cicdapplication/cforcweb:latest
          
